export const INPUT_NUM = "inputNum"
export const OPERATER = "operater"
export const POSI_AND_NEGA = "posiAndNega"
export const ONE_HUNDREDTH = "oneHundredth"
export const DECIMAL_POINT = "decimalPoint"
export const CLEAR = "clear"
export const ALL_CLEAR = "allClear"
export const EQUAL = "equal"
